version: '3.3'

services:
  prueva-postgres:
    container_name: prueva-postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin2020
      - POSTGRES_DB=Finvero
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
